[program:orca-frontend]
command=/bin/bash -c 'yarn dev --hostname "$HOST" --port "$PORT"'
directory=/app/orca-frontend
environment=HOST="0.0.0.0",PORT="3000"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/orca-frontend.err.log
stdout_logfile=/var/log/supervisor/orca-frontend.out.log
stopasgroup=true
killasgroup=true