"""initial schema

Revision ID: 729be30b0cb2
Revises: 
Create Date: 2026-08-29 05:16:41.655673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '729be30b0cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgresql() -> bool:
    """Check if we're running against PostgreSQL."""
    return op.get_bind().dialect.name == 'postgresql'


def _array_type(item_type: type) -> type:
    """Return ARRAY type for PostgreSQL, JSON for SQLite."""
    if _is_postgresql():
        return sa.ARRAY(item_type)
    return sa.JSON()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # For SQLite, use TEXT for geom; for PostgreSQL, use PostGIS Geography
    if _is_postgresql():
        geom_type = geoalchemy2.types.Geography(
            geometry_type='POINT', srid=4326, dimension=2,
            from_text='ST_GeogFromText', name='geography', nullable=False,
            spatial_index=False
        )
    else:
        geom_type = sa.Text()
    
    op.create_table('argo_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_number', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('profile_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geom_type, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('qc_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_number', 'cycle_number', name='uq_platform_cycle')
    )
    
    if _is_postgresql():
        op.create_index('idx_argo_profiles_geom', 'argo_profiles', ['geom'], unique=False, postgresql_using='gist')
    else:
        op.create_index('idx_argo_profiles_geom', 'argo_profiles', ['geom'], unique=False)
    
    op.create_index(op.f('ix_argo_profiles_platform_number'), 'argo_profiles', ['platform_number'], unique=False)
    op.create_index(op.f('ix_argo_profiles_profile_time'), 'argo_profiles', ['profile_time'], unique=False)
    
    op.create_table('dataset_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True),
    sa.Column('record_count', sa.BigInteger(), nullable=False),
    sa.Column('profile_count', sa.BigInteger(), nullable=False),
    sa.Column('float_count', sa.BigInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('query_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('normalized_intent', sa.String(length=100), nullable=True),
    sa.Column('structured_query', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('idx_query_runs_session_created', 'query_runs', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_runs_session_id'), 'query_runs', ['session_id'], unique=False)
    
    op.create_table('argo_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('pressure_dbar', sa.Float(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('salinity_psu', sa.Float(), nullable=True),
    sa.Column('oxygen_umol_kg', sa.Float(), nullable=True),
    sa.Column('chlorophyll', sa.Float(), nullable=True),
    sa.Column('temperature_qc', sa.Integer(), nullable=True),
    sa.Column('salinity_qc', sa.Integer(), nullable=True),
    sa.Column('oxygen_qc', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['argo_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('idx_argo_obs_profile', 'argo_observations', ['profile_id'], unique=False)
    
    if _is_postgresql():
        op.create_index('idx_argo_obs_salinity', 'argo_observations', ['salinity_psu'], unique=False, postgresql_where='salinity_psu IS NOT NULL')
        op.create_index('idx_argo_obs_temp', 'argo_observations', ['temperature_c'], unique=False, postgresql_where='temperature_c IS NOT NULL')
    else:
        op.create_index('idx_argo_obs_salinity', 'argo_observations', ['salinity_psu'], unique=False)
        op.create_index('idx_argo_obs_temp', 'argo_observations', ['temperature_c'], unique=False)
    
    op.create_index(op.f('ix_argo_observations_depth_m'), 'argo_observations', ['depth_m'], unique=False)
    op.create_index(op.f('ix_argo_observations_profile_id'), 'argo_observations', ['profile_id'], unique=False)
    
    op.create_table('evidence_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_run_id', sa.BigInteger(), nullable=False),
    sa.Column('float_ids', _array_type(sa.Integer()), nullable=False),
    sa.Column('profile_count', sa.BigInteger(), nullable=False),
    sa.Column('observation_count', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.JSON(), nullable=False),
    sa.Column('depth_range', sa.JSON(), nullable=True),
    sa.Column('time_range', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('data_freshness', sa.JSON(), nullable=False),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('confidence_components', sa.JSON(), nullable=False),
    sa.Column('limitations', _array_type(sa.Text()), nullable=False),
    sa.Column('source_identifiers', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_errors', _array_type(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_evidence_records_query_run_id'), 'evidence_records', ['query_run_id'], unique=False)
    
    op.create_table('narratives',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_run_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('numeric_claims', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_narratives_query_run_id'), 'narratives', ['query_run_id'], unique=False)
    
    op.create_table('scenario_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_run_id', sa.BigInteger(), nullable=False),
    sa.Column('variable', sa.String(length=100), nullable=False),
    sa.Column('region', sa.JSON(), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('trend_window', sa.JSON(), nullable=False),
    sa.Column('projection_horizon', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('assumptions', _array_type(sa.Text()), nullable=False),
    sa.Column('uncertainty_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_scenario_runs_query_run_id'), 'scenario_runs', ['query_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_runs_query_run_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_narratives_query_run_id'), table_name='narratives')
    op.drop_table('narratives')
    op.drop_index(op.f('ix_evidence_records_query_run_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_argo_observations_profile_id'), table_name='argo_observations')
    op.drop_index(op.f('ix_argo_observations_depth_m'), table_name='argo_observations')
    op.drop_index('idx_argo_obs_temp', table_name='argo_observations')
    op.drop_index('idx_argo_obs_salinity', table_name='argo_observations')
    op.drop_index('idx_argo_obs_profile', table_name='argo_observations')
    op.drop_table('argo_observations')
    op.drop_index(op.f('ix_query_runs_session_id'), table_name='query_runs')
    op.drop_index('idx_query_runs_session_created', table_name='query_runs')
    op.drop_table('query_runs')
    op.drop_table('dataset_snapshots')
    op.drop_index(op.f('ix_argo_profiles_profile_time'), table_name='argo_profiles')
    op.drop_index(op.f('ix_argo_profiles_platform_number'), table_name='argo_profiles')
    op.drop_index('idx_argo_profiles_geom', table_name='argo_profiles')
    op.drop_table('argo_profiles')
    # ### end Alembic commands ###