from typing import Dict, List, Optional
from pydantic import BaseModel, Field

class Location(BaseModel):
    lat: float = Field(..., description="Latitude of the user or query location")
    lon: float = Field(..., description="Longitude of the user or query location")

class Weather(BaseModel):
    wind: float = Field(..., description="Wind speed in knots or km/h")
    rain: float = Field(..., description="Rainfall volume in mm")
    visibility: float = Field(..., description="Visibility range in km")

class Ocean(BaseModel):
    wave_height: float = Field(..., description="Wave height in meters")
    current_speed: float = Field(..., description="Ocean current speed in knots")
    sst: float = Field(..., description="Sea Surface Temperature in Celsius")

class WarningInfo(BaseModel):
    source: str = Field(..., description="Source of the warning, e.g., 'IMD'")
    type: str = Field(..., description="Type of warning, e.g., 'Fishermen Warning'")
    status: str = Field(..., description="Status of the warning, e.g., 'ACTIVE' or 'INACTIVE'")

class FishingSuitability(BaseModel):
    suitability: float = Field(..., description="Suitability score between 0 and 1")

class Risk(BaseModel):
    score: float = Field(..., description="Risk score between 0 and 1")
    level: str = Field(..., description="Categorical risk level, e.g., 'HIGH', 'MODERATE', 'LOW'")

class RiskEscalation(BaseModel):
    probability: float = Field(..., description="Probability of risk escalation between 0 and 1")
    trend: str = Field(..., description="Trend of risk, e.g., 'INCREASING', 'DECREASING', 'STABLE'")

class RouteInfo(BaseModel):
    risk: float = Field(..., description="Aggregated route risk score between 0 and 1")

class RAGDocument(BaseModel):
    title: str = Field(..., description="Title of the retrieved document or advisory")
    source: str = Field(..., description="Source agency or category, e.g., 'IMD', 'INCOIS'")
    content: str = Field(..., description="The actual text content of the retrieved chunk")

class OrcaState(BaseModel):
    """
    This is the master state object that gets passed around the LangGraph workflow.
    It culminates into the massive JSON payload injected into the final LLM prompt.
    """
    query: str = Field(..., description="The original user query")
    intent_type: Optional[str] = Field(None, description="Set by the router: 'simple' or 'complex'")
    language: Optional[str] = Field(None, description="BCP-47-ish code: en/ml/hi/ta")
    history: List[Dict[str, str]] = Field(default_factory=list,
        description="Last turns [{role, text}] for follow-up resolution")
    
    # Populated by Query Extraction / User Input
    location: Optional[Location] = None
    
    # Populated by Live Data Agent
    weather: Optional[Weather] = None
    ocean: Optional[Ocean] = None
    warnings: List[WarningInfo] = Field(default_factory=list)
    data_sources: Dict[str, str] = Field(default_factory=dict)
    telemetry_live: bool = False
    
    # Populated by ML Node / Geospatial Agent
    fishing: Optional[FishingSuitability] = None
    risk: Optional[Risk] = None
    risk_escalation: Optional[RiskEscalation] = None
    route: Optional[RouteInfo] = None
    
    # Populated by RAG Agent
    rag: List[RAGDocument] = Field(default_factory=list)

    # The final output generated by the LLM
    final_response: Optional[str] = Field(None, description="The final text response generated by the LLM")
